### ISSUE TITLE
Game project issue - refresh cards 

### ISSUE THREAD

**Issue by katherine-kania** [sei-ec-remote/project-1-issues#29]
### What's the problem you're trying to solve?
I am trying to remove the current class list of cards and recreate a new set for the next player turn.

### Post any code you think might be relevant (one fenced block per file)
```
 const reshuffleCards = () => {
            console.log('these are the old cards', cardSpace)
            const oldCards = cardSpace.getElementsByClassName('cardDiv')
            remove(oldCards)

            const cards = deckBuilder()
            randomCard(cards)
        }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

```
app.js:150 Uncaught ReferenceError: remove is not defined
    at reshuffleCards (app.js:150:13)
    at matched (app.js:129:13)
    at compareCards (app.js:108:17)
    at HTMLDivElement.pushChoices (app.js:96:17)
reshuffleCards @ app.js:150
matched @ app.js:129
compareCards @ app.js:108
pushChoices @ app.js:96

```

### What is your best guess as to the source of the problem?
I tried removeChild and it didn't work either. 

### What things have you already tried to solve the problem?
I tried removeChild and and reload oldCards. Neither methods worked. I received the same error. 

### Paste a link to your repository here
https://github.com/katherine-kania/game-project-1.git

**Comment by katherine-kania** [comment]
Thank you Doire and Tom!
I got the switch player and points working properly.

Now I will work on trying to get the set of cards to "refresh" or grab new values between turns.

**Comment by katherine-kania** [comment]
I was able to get the used cards to change to a new color and letter value. Reading up more on HTMLElement.dataset helped!

```
  const replaceUsed = () => {
            // console.log ('this is the replace card', playerChoiceCards[0].dataset)
            for (let i = 0; i < playerChoiceCards.length; i++){
                const random = Math.floor(Math.random() * 27)
                const cardLetter = cards[random].letter
                const cardColor = cards[random].color
                console.log('these are the random letters', cardLetter)
                playerChoiceCards[i].dataset.color = cardColor
                playerChoiceCards[i].dataset.letter = cardLetter
                playerChoiceCards[i].style.color = cardColor
                playerChoiceCards[i].innerHTML = cardLetter 
                playerChoiceCards[i].style.backgroundColor = 'snow'
            }
        }

```
